In [1]:
import pandas as pd
pd.set_option('display.float_format', '{:,.2f}'.format)
#SETTING AND RESETTING DISPLAY OPTIONS
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.reset_option('display.max_rows')
#pd.reset_option('display.max_columns')

df = pd.read_csv('data/JFK.csv')
df

,Activity Period,Airport Code,Terminal Port,Marketing Airline Name,Direction,Market,World Region,Revenue Passenger Volume,Non-Revenue Passenger Volume,Freight Volume,Mail Volume,Total Flights
0,2000-01-01 00:00:00.0000000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,641
1,2000-02-01 00:00:00.0000000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,763
2,2000-03-01 00:00:00.0000000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,777
3,2000-04-01 00:00:00.0000000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,775
4,2000-05-01 00:00:00.0000000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,841
...,...,...,...,...,...,...,...,...,...,...,...,...
662397,2025-05-01 00:00:00.0000000,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,CARIBBEAN + BERMUDA,0,0,0.00,0.00,0
662398,2025-05-01 00:00:00.0000000,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,CENTRAL AND SOUTH AMERICA,0,0,0.00,0.00,0
662399,2025-05-01 00:00:00.0000000,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,MEXICO,0,0,0.00,0.00,0
662400,2025-05-01 00:00:00.0000000,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,TRANSATLANTIC,3255,0,0.00,0.00,23
662401,2025-05-01 00:00:00.0000000,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,TRANSPACIFIC,0,0,0.00,0.00,0

In [9]:
df['Activity Period'] = df['Activity Period'].str.split('-', n=1).str[0]
df

,Activity Period,Airport Code,Terminal Port,Marketing Airline Name,Direction,Market,World Region,Revenue Passenger Volume,Non-Revenue Passenger Volume,Freight Volume,Mail Volume,Total Flights
0,2000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,641
1,2000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,763
2,2000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,777
3,2000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,775
4,2000,EWR,General Aviation,General Aviation,Inbound,Domestic,DOMESTIC,0,0,0.00,0.00,841
...,...,...,...,...,...,...,...,...,...,...,...,...
662397,2025,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,CARIBBEAN + BERMUDA,0,0,0.00,0.00,0
662398,2025,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,CENTRAL AND SOUTH AMERICA,0,0,0.00,0.00,0
662399,2025,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,MEXICO,0,0,0.00,0.00,0
662400,2025,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,TRANSATLANTIC,3255,0,0.00,0.00,23
662401,2025,SWF,PASSENGER TERMINAL,PLAY AIRLINES,Outbound,International,TRANSPACIFIC,0,0,0.00,0.00,0

In [13]:
df['Direction'].value_counts()

Inbound     332921
Outbound    329481
Name: Direction, dtype: int64

In [14]:
cond1 = df['Airport Code'] == 'JFK'
cond2 = df['Activity Period'] == '2024'
cond3 = df['Direction'] == 'Outbound'

jfk24 = df[cond1 & cond2 & cond3]
jfk24

,Activity Period,Airport Code,Terminal Port,Marketing Airline Name,Direction,Market,World Region,Revenue Passenger Volume,Non-Revenue Passenger Volume,Freight Volume,Mail Volume,Total Flights
1717,2024,JFK,General Aviation,General Aviation,Outbound,Domestic,DOMESTIC,0,0,0.00,0.00,628
1718,2024,JFK,General Aviation,General Aviation,Outbound,Domestic,DOMESTIC,0,0,0.00,0.00,630
1719,2024,JFK,General Aviation,General Aviation,Outbound,Domestic,DOMESTIC,0,0,0.00,0.00,539
1720,2024,JFK,General Aviation,General Aviation,Outbound,Domestic,DOMESTIC,0,0,0.00,0.00,675
1721,2024,JFK,General Aviation,General Aviation,Outbound,Domestic,DOMESTIC,0,0,0.00,0.00,853
...,...,...,...,...,...,...,...,...,...,...,...,...
588829,2024,JFK,TERMINAL 8,XIAMEN AIRLINES,Outbound,International,CARIBBEAN + BERMUDA,0,0,0.00,0.00,0
588830,2024,JFK,TERMINAL 8,XIAMEN AIRLINES,Outbound,International,CENTRAL AND SOUTH AMERICA,0,0,0.00,0.00,0
588831,2024,JFK,TERMINAL 8,XIAMEN AIRLINES,Outbound,International,MEXICO,0,0,0.00,0.00,0
588832,2024,JFK,TERMINAL 8,XIAMEN AIRLINES,Outbound,International,TRANSATLANTIC,0,0,0.00,0.00,0
588833,2024,JFK,TERMINAL 8,XIAMEN AIRLINES,Outbound,International,TRANSPACIFIC,0,0,0.00,0.00,0

In [15]:
jfk24['Total Flights'].sum()

234302

In [19]:
passengers24 = jfk24['Revenue Passenger Volume'].sum() + jfk24['Non-Revenue Passenger Volume'].sum()
passengers24

32283197

In [20]:
jfk24['Revenue Passenger Volume'].sum()

31497271